/* eslint-disable @typescript-eslint/no-explicit-any -- Sanity's fluent client is intentionally represented by a minimal mutable test double. */
import assert from 'node:assert/strict'; import test from 'node:test';
// @ts-expect-error Node executes TypeScript directly.
import { generateSpotifyThumbnail } from './generate-spotify-thumbnail.ts';
const source='https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC', asset='image-abcdef123-10x10-webp', sha='a'.repeat(64);
function harness(overrides:Record<string,unknown>={}){let document:any={_id:'drafts.link1',_rev:'rev1',_type:'link',url:source};let patchValue:any;let uploads=0;const client:any={getDocument:async()=>({...document}),assets:{upload:async()=>{uploads++;return{_id:asset}}},patch:()=>{const builder:any={ifRevisionId:()=>builder,set:(value:any)=>{patchValue=value;return builder},commit:async()=>({})};return builder}};return{dependencies:{client,oEmbed:async()=>({ok:true,title:'Title',thumbnailUrl:'https://i.scdn.co/image/abc',responseBytes:10}),download:async()=>({ok:true,downloadedBytes:10,thumbnail:{bytes:Buffer.from('webp'),mimeType:'image/webp',extension:'webp',width:10,height:10,byteLength:4,sha256:sha}}),now:()=>new Date('2026-07-16T12:00:00.000Z'),...overrides},getPatch:()=>patchValue,getUploads:()=>uploads,setDocument:(value:any)=>{document=value}}}
const command={documentId:'drafts.link1',expectedRevision:'rev1',sourceCanonicalUrl:source,replacementConfirmed:false};
test('generates track thumbnail with safe image reference and provenance',async()=>{const h=harness();const result=await generateSpotifyThumbnail(command,h.dependencies as any);assert.deepEqual(result,{ok:true,documentId:'drafts.link1',assetId:asset,sha256:sha});assert.deepEqual(h.getPatch(),{thumbnail:{_type:'image',asset:{_type:'reference',_ref:asset}},thumbnailAutomation:{_type:'thumbnailAutomation',provider:'spotify',sourceCanonicalUrl:source,fetchedAt:'2026-07-16T12:00:00.000Z',assetRef:asset,sha256:sha,method:'spotify-oembed-v1'}});assert.equal(JSON.stringify(h.getPatch()).includes('thumbnailUrl'),false)});
test('supports albums and rejects playlists',async()=>{const album='https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX';const h=harness();h.setDocument({_id:'drafts.link1',_rev:'rev1',_type:'link',url:album});assert.equal((await generateSpotifyThumbnail({...command,sourceCanonicalUrl:album},h.dependencies as any)).ok,true);const p=harness();p.setDocument({_id:'drafts.link1',_rev:'rev1',_type:'link',url:'https://open.spotify.com/playlist/4uLU6hMCjMI75M1A2tKUQC'});assert.deepEqual(await generateSpotifyThumbnail({...command,sourceCanonicalUrl:'https://open.spotify.com/playlist/4uLU6hMCjMI75M1A2tKUQC'},p.dependencies as any),{ok:false,reason:'unsupported-source'})});
test('rejects missing, wrong type, stale source and revision',async()=>{for(const [doc,expected] of [[undefined,'document-not-found'],[{_id:'drafts.link1',_rev:'rev1',_type:'log',url:source},'wrong-document-type'],[{_id:'drafts.link1',_rev:'other',_type:'link',url:source},'document-conflict']] as const){const h=harness();(h.dependencies.client as any).getDocument=async()=>doc;assert.deepEqual(await generateSpotifyThumbnail(command,h.dependencies as any),{ok:false,reason:expected})}const h=harness();assert.deepEqual(await generateSpotifyThumbnail({...command,sourceCanonicalUrl:source+'x'},h.dependencies as any),{ok:false,reason:'source-changed'})});
test('protects manual and automatic thumbnails until confirmed',async()=>{const h=harness();h.setDocument({_id:'drafts.link1',_rev:'rev1',_type:'link',url:source,thumbnail:{asset:{_ref:'image-manual-10x10-webp'}}});assert.deepEqual(await generateSpotifyThumbnail(command,h.dependencies as any),{ok:false,reason:'replacement-confirmation-required'});assert.equal((await generateSpotifyThumbnail({...command,replacementConfirmed:true},h.dependencies as any)).ok,true)});
test('provider or download failure prevents upload and patch',async()=>{for(const override of [{oEmbed:async()=>({ok:false,reason:'provider-not-found'})},{download:async()=>({ok:false,reason:'thumbnail-invalid'})}]){const h=harness(override);assert.equal((await generateSpotifyThumbnail(command,h.dependencies as any)).ok,false);assert.equal(h.getUploads(),0);assert.equal(h.getPatch(),undefined)}});
test('upload failure and second-read conflict never patch newer work',async()=>{const upload=harness();(upload.dependencies.client as any).assets.upload=async()=>{throw new Error('fail')};assert.deepEqual(await generateSpotifyThumbnail(command,upload.dependencies as any),{ok:false,reason:'sanity-upload-failed'});const conflict=harness();let reads=0;(conflict.dependencies.client as any).getDocument=async()=>{reads++;return{_id:'drafts.link1',_rev:reads===1?'rev1':'rev2',_type:'link',url:source}};assert.deepEqual(await generateSpotifyThumbnail(command,conflict.dependencies as any),{ok:false,reason:'document-conflict'});assert.equal(conflict.getPatch(),undefined)});
