import assert from 'node:assert/strict'; import test from 'node:test';
// @ts-expect-error Node executes TypeScript directly.
import { fetchSpotifyOEmbed } from './spotify-oembed.ts';
const source='https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC';
const liveSource='https://open.spotify.com/track/3MayfpbIgeGye2ilwK3LII';
const liveThumbnail='https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02eb2087dcd1eb61f833bdedff';
const valid={provider_name:'Spotify',provider_url:'https://spotify.com',type:'rich',title:'Test',thumbnail_url:'https://i.scdn.co/image/abc',thumbnail_width:300,thumbnail_height:300,html:'<iframe>ignored</iframe>'};
const response=(body:unknown,status=200,type='application/json')=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':type}});
test('extracts narrow metadata and ignores html',async()=>{let calls=0;const result=await fetchSpotifyOEmbed(source,async(url,init)=>{calls++;assert.equal(url.origin+url.pathname,'https://open.spotify.com/oembed');assert.equal(url.searchParams.get('url'),source);assert.equal((init.headers as Record<string,string>).Authorization,undefined);assert.equal((init.headers as Record<string,string>).Cookie,undefined);return response(valid)});assert.equal(calls,1);assert.deepEqual(result,{ok:true,title:'Test',thumbnailUrl:'https://i.scdn.co/image/abc',reportedWidth:300,reportedHeight:300,responseBytes:JSON.stringify(valid).length})});
test('preserves the exact live Spotify CDN thumbnail fixture as narrow metadata',async()=>{const fixture={...valid,title:'Live track fixture',thumbnail_url:liveThumbnail};assert.deepEqual(await fetchSpotifyOEmbed(liveSource,async()=>response(fixture)),{ok:true,title:'Live track fixture',thumbnailUrl:liveThumbnail,reportedWidth:300,reportedHeight:300,responseBytes:JSON.stringify(fixture).length})});
test('handles missing thumbnail and unsafe responses',async()=>{assert.deepEqual(await fetchSpotifyOEmbed(source,async()=>response({...valid,thumbnail_url:null})),{ok:false,reason:'no-thumbnail'});for(const res of [response('{',200),response(valid,200,'text/html'),response({...valid,provider_name:'Other'}),response([],200)])assert.equal((await fetchSpotifyOEmbed(source,async()=>res)).ok,false)});
for(const [status,reason] of [[404,'provider-not-found'],[429,'provider-rate-limited'],[500,'provider-unavailable'],[418,'unsafe-provider-response'],[302,'unsafe-provider-response']] as const)test(`maps ${status}`,async()=>assert.deepEqual(await fetchSpotifyOEmbed(source,async()=>response({},status)),{ok:false,reason}));
test('rejects oversized body and timeout without retry',async()=>{let calls=0;assert.equal((await fetchSpotifyOEmbed(source,async()=>{calls++;return response('x'.repeat(256*1024+1))})).ok,false);assert.equal(calls,1);assert.deepEqual(await fetchSpotifyOEmbed(source,async()=>{throw new DOMException('timeout','TimeoutError')}),{ok:false,reason:'provider-timeout'})});
test('endpoint cannot be caller controlled',async()=>assert.deepEqual(await fetchSpotifyOEmbed('https://evil.test/track/4uLU6hMCjMI75M1A2tKUQC',async()=>{throw new Error('must not call')}),{ok:false,reason:'invalid-source'}));
