import assert from 'node:assert/strict'; import test from 'node:test'; import sharp from 'sharp';
// @ts-expect-error Node executes TypeScript directly.
import { createSpotifyRequestOptions, createValidatedLookup, downloadSpotifyThumbnail, isPublicAddress } from './spotify-thumbnail-download.ts';
const url='https://i.scdn.co/image/abc';
const live='https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02eb2087dcd1eb61f833bdedff';
async function* body(bytes:Uint8Array){yield bytes}
test('downloads approved bytes and returns only sanitized WebP',async()=>{const remote=await sharp({create:{width:10,height:10,channels:3,background:'red'}}).png().toBuffer();for(const approved of [url,live]){const result=await downloadSpotifyThumbnail(approved,async(received)=>{assert.equal(received.url,approved);assert.equal(received.hostname,new URL(approved).hostname);return{status:200,contentType:'image/png',body:body(remote)}});assert.equal(result.ok,true);if(result.ok){assert.equal((await sharp(result.thumbnail.bytes).metadata()).format,'webp');assert.notDeepEqual(result.thumbnail.bytes,remote)}}});
test('binds HTTPS, TLS, and DNS lookup to the exact validated hostname',()=>{for(const approved of [url,live]){const validated={ok:true as const,url:approved,hostname:new URL(approved).hostname as 'i.scdn.co'|'image-cdn-fa.spotifycdn.com'};const options=createSpotifyRequestOptions(validated);assert.equal(options.hostname,validated.hostname);assert.equal(options.servername,validated.hostname);assert.equal(options.port,443);assert.equal(options.path,new URL(approved).pathname);assert.equal(typeof options.lookup,'function')}});
test('honors the Node 24 all-address lookup contract after validating every answer',async()=>{const hostname='image-cdn-fa.spotifycdn.com';const lookup=createValidatedLookup(hostname,(received,callback)=>{assert.equal(received,hostname);callback(null,[{address:'8.8.8.8',family:4},{address:'2606:4700:4700::1111',family:6}])});await new Promise<void>((resolve,reject)=>lookup(hostname,{all:true},(error,addresses)=>{if(error)return reject(error);assert.deepEqual(addresses,[{address:'8.8.8.8',family:4},{address:'2606:4700:4700::1111',family:6}]);resolve()}));const blocked=createValidatedLookup(hostname,(_received,callback)=>callback(null,[{address:'127.0.0.1',family:4}]));await new Promise<void>((resolve)=>blocked(hostname,{all:true},(error,addresses)=>{assert.equal(error?.code,'EACCES');assert.deepEqual(addresses,[]);resolve()}))});
test('rejects redirects, status, HTML, SVG and oversized streams',async()=>{for(const response of [{status:302,contentType:'image/png',body:body(new Uint8Array())},{status:500,contentType:'image/png',body:body(new Uint8Array())},{status:200,contentType:'text/html',body:body(new Uint8Array())},{status:200,contentType:'image/svg+xml',body:body(new Uint8Array())}])assert.equal((await downloadSpotifyThumbnail(url,async()=>response)).ok,false);async function* huge(){yield new Uint8Array(8*1024*1024+1)}assert.deepEqual(await downloadSpotifyThumbnail(url,async()=>({status:200,contentType:'image/png',body:huge()})),{ok:false,reason:'thumbnail-too-large'})});
test('rejects malformed image and unsafe URL',async()=>{assert.deepEqual(await downloadSpotifyThumbnail(url,async()=>({status:200,contentType:'image/png',body:body(new TextEncoder().encode('bad'))})),{ok:false,reason:'thumbnail-invalid'});assert.deepEqual(await downloadSpotifyThumbnail('https://evil.test/image/x',async()=>{throw new Error()}),{ok:false,reason:'unsafe-thumbnail-url'})});
test('classifies public and blocked IP families',()=>{for(const ip of ['8.8.8.8','2606:4700:4700::1111'])assert.equal(isPublicAddress(ip),true);for(const ip of ['127.0.0.1','10.0.0.1','169.254.1.1','100.64.0.1','192.168.1.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1'])assert.equal(isPublicAddress(ip),false)});
