import assert from 'node:assert/strict'; import test from 'node:test'; import sharp from 'sharp';
// @ts-expect-error Node executes TypeScript directly.
import { downloadSpotifyThumbnail, isPublicAddress } from './spotify-thumbnail-download.ts';
const url='https://i.scdn.co/image/abc';
async function* body(bytes:Uint8Array){yield bytes}
test('downloads approved bytes and returns only sanitized WebP',async()=>{const remote=await sharp({create:{width:10,height:10,channels:3,background:'red'}}).png().toBuffer();const result=await downloadSpotifyThumbnail(url,async(received)=>{assert.equal(received.toString(),url);return{status:200,contentType:'image/png',body:body(remote)}});assert.equal(result.ok,true);if(result.ok){assert.equal((await sharp(result.thumbnail.bytes).metadata()).format,'webp');assert.notDeepEqual(result.thumbnail.bytes,remote)}});
test('rejects redirects, status, HTML, SVG and oversized streams',async()=>{for(const response of [{status:302,contentType:'image/png',body:body(new Uint8Array())},{status:500,contentType:'image/png',body:body(new Uint8Array())},{status:200,contentType:'text/html',body:body(new Uint8Array())},{status:200,contentType:'image/svg+xml',body:body(new Uint8Array())}])assert.equal((await downloadSpotifyThumbnail(url,async()=>response)).ok,false);async function* huge(){yield new Uint8Array(8*1024*1024+1)}assert.deepEqual(await downloadSpotifyThumbnail(url,async()=>({status:200,contentType:'image/png',body:huge()})),{ok:false,reason:'thumbnail-too-large'})});
test('rejects malformed image and unsafe URL',async()=>{assert.deepEqual(await downloadSpotifyThumbnail(url,async()=>({status:200,contentType:'image/png',body:body(new TextEncoder().encode('bad'))})),{ok:false,reason:'thumbnail-invalid'});assert.deepEqual(await downloadSpotifyThumbnail('https://evil.test/image/x',async()=>{throw new Error()}),{ok:false,reason:'unsafe-thumbnail-url'})});
test('classifies public and blocked IP families',()=>{for(const ip of ['8.8.8.8','2606:4700:4700::1111'])assert.equal(isPublicAddress(ip),true);for(const ip of ['127.0.0.1','10.0.0.1','169.254.1.1','100.64.0.1','192.168.1.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1'])assert.equal(isPublicAddress(ip),false)});
