'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, FileAudio, ListMusic, LoaderCircle, Pause, Play, Repeat, Repeat1, Shuffle, SkipBack, SkipForward } from 'lucide-react';
import { PlaybackQueue } from './playback-queue';
import { usePlayer } from './player-provider';

function time(value: number) { if (!Number.isFinite(value)) return '0:00'; return `${Math.floor(value / 60)}:${Math.floor(value % 60).toString().padStart(2, '0')}`; }
export function NowPlayingScreen() {
  const router = useRouter(); const player = usePlayer(); const beat = player.beat;
  if (!beat) return <main className="mx-auto flex min-h-[70vh] max-w-xl flex-col items-center justify-center text-center"><p className="text-[11px] uppercase tracking-[0.3em] text-cobalt">Now Playing</p><h1 className="mt-4 text-3xl font-semibold text-white">Nothing queued yet</h1><p className="mt-3 text-sm text-mist/60">Choose a Beat, Release, or Main Library shuffle to begin.</p><Link href="/player" className="mt-7 rounded-full bg-white px-6 py-3 text-sm font-semibold text-ink">Open Player</Link></main>;
  const cover = beat.coverArtUrl || beat.lane?.fallbackCoverArtUrl; const RepeatIcon = player.repeatMode === 'one' ? Repeat1 : Repeat;
  return <main className="mx-auto max-w-2xl pb-8"><header className="flex items-center justify-between"><button type="button" onClick={() => window.history.length > 1 ? router.back() : router.push('/player')} className="grid h-11 w-11 place-items-center rounded-full border border-white/10 bg-white/5 text-white" aria-label="Back"><ArrowLeft className="h-5 w-5" /></button><div className="min-w-0 px-4 text-center"><p className="text-[10px] uppercase tracking-[0.28em] text-cobalt">Now Playing</p><p className="mt-1 truncate text-xs text-mist/55">{player.context?.title}</p></div><span className="h-11 w-11" /></header>
    <section className="mx-auto mt-7 max-w-md"><div className="aspect-square overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-cobalt/30 via-white/5 to-ember/25 shadow-[0_28px_80px_rgba(0,0,0,0.5)]">{cover ? <img src={cover} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><ListMusic className="h-16 w-16 text-white/15" /></div>}</div><div className="mt-7"><h1 className="truncate text-2xl font-semibold text-white">{beat.title}</h1><p className="mt-1 truncate text-sm text-mist/60">{beat.lane?.name || 'Unassigned lane'}</p>{player.context?.type === 'release' ? <p className="mt-2 truncate text-xs font-medium text-cobalt">Release · {player.context.title}</p> : null}</div>
      <input type="range" min={0} max={player.duration || 0} step={0.1} value={Math.min(player.currentTime, player.duration || 0)} onChange={(event) => player.seek(Number(event.target.value))} disabled={!player.duration} aria-label="Playback progress" className="mt-6 h-1 w-full cursor-pointer accent-cobalt disabled:opacity-40" /><div className="mt-2 flex justify-between font-mono text-[11px] text-mist/45"><span>{time(player.currentTime)}</span><span>{time(player.duration)}</span></div>
      <div className="mt-5 flex items-center justify-between"><button type="button" onClick={player.cycleRepeatMode} className={`relative grid h-12 w-12 place-items-center rounded-full ${player.repeatMode === 'off' ? 'text-mist/40' : 'bg-cobalt/15 text-cobalt'}`} aria-label={`Repeat ${player.repeatMode}`}><RepeatIcon className="h-5 w-5" /><span className="absolute -bottom-1 text-[8px] uppercase">{player.repeatMode}</span></button><button type="button" onClick={() => void player.previous()} disabled={!player.hasPrevious && player.currentTime <= 3} className="grid h-14 w-14 place-items-center text-white disabled:text-mist/20" aria-label="Previous Beat"><SkipBack className="h-7 w-7" fill="currentColor" /></button><button type="button" onClick={() => void player.togglePlayback()} disabled={player.isLoading} className="grid h-16 w-16 place-items-center rounded-full bg-white text-ink disabled:opacity-50" aria-label={player.isPlaying ? 'Pause' : 'Play'}>{player.isLoading ? <LoaderCircle className="h-6 w-6 animate-spin" /> : player.isPlaying ? <Pause className="h-6 w-6" fill="currentColor" /> : <Play className="ml-1 h-6 w-6" fill="currentColor" />}</button><button type="button" onClick={() => void player.next()} disabled={!player.hasNext} className="grid h-14 w-14 place-items-center text-white disabled:text-mist/20" aria-label="Next Beat"><SkipForward className="h-7 w-7" fill="currentColor" /></button><span className={`grid h-12 w-12 place-items-center rounded-full ${player.shuffle ? 'bg-cobalt/15 text-cobalt' : 'text-mist/25'}`} title={player.shuffle ? 'Shuffled queue' : 'Queue is not shuffled'}><Shuffle className="h-5 w-5" /></span></div>
      {player.error ? <p className="mt-4 text-center text-xs text-red-300">{player.error}</p> : null}{beat.slug ? <Link href={`/player/beats/${beat.slug}`} className="mt-6 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-white/10 text-sm text-mist/70 hover:bg-white/5 hover:text-white"><FileAudio className="h-4 w-4" /> Open Beat File</Link> : <button type="button" disabled className="mt-6 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-white/10 text-sm text-mist/35"><FileAudio className="h-4 w-4" /> Beat File unavailable</button>}</section>
    <section className="mt-9 rounded-[1.75rem] border border-white/10 bg-white/[0.035] p-5"><PlaybackQueue compact /></section></main>;
}
