'use client';
import { useCallback, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Expand, FileAudio, ListMusic, LoaderCircle, Pause, Play, Repeat, Repeat1, Shuffle, SkipBack, SkipForward } from 'lucide-react';
import { ListeningMode } from './listening-mode';
import { PlaybackQueue } from './playback-queue';
import { ProtocolLabel } from './presentation-primitives';
import { usePlayer } from './player-provider';
function time(value: number) { if (!Number.isFinite(value)) return '0:00'; return `${Math.floor(value / 60)}:${Math.floor(value % 60).toString().padStart(2, '0')}`; }
export function NowPlayingScreen() { const router = useRouter(); const player = usePlayer(); const beat = player.beat; const [isListeningModeOpen, setListeningModeOpen] = useState(false); const listeningModeEntryRef = useRef<HTMLButtonElement>(null);
  const closeListeningMode = useCallback(() => { setListeningModeOpen(false); requestAnimationFrame(() => listeningModeEntryRef.current?.focus()); }, []);
  if (!beat) return <main className="mx-auto flex min-h-[70vh] max-w-xl flex-col items-center justify-center text-center"><ProtocolLabel>Now Playing</ProtocolLabel><h1 className="mt-4 text-3xl font-semibold text-[var(--text-primary)]">Nothing queued yet</h1><p className="type-small mt-3">Choose a Beat, Release, or Main Library shuffle to begin.</p><Link href="/player" className="focusable-surface mt-7 inline-flex min-h-11 items-center bg-[var(--text-primary)] px-6 text-sm font-semibold text-[var(--bg-0)]">Open Player</Link></main>;
  const cover = beat.coverArtUrl || beat.lane?.fallbackCoverArtUrl; const RepeatIcon = player.repeatMode === 'one' ? Repeat1 : Repeat; const progress = player.duration > 0 ? Math.min(100, Math.max(0, player.currentTime / player.duration * 100)) : 0; const slug = beat.sourceType === 'version' ? beat.parentBeatSlug : beat.slug;
  return <><main inert={isListeningModeOpen ? true : undefined} aria-hidden={isListeningModeOpen ? true : undefined} className="mx-auto w-full max-w-[var(--player-measure)] pb-8"><header className="flex items-center justify-between"><button type="button" onClick={() => window.history.length > 1 ? router.back() : router.push('/player')} className="grid h-11 w-11 place-items-center text-[var(--text-primary)]" aria-label="Back"><ArrowLeft className="h-5 w-5" /></button><div className="min-w-0 px-4 text-center"><ProtocolLabel>Now Playing</ProtocolLabel><p className="type-metadata mt-1 truncate">{player.context?.title}</p></div><span className="h-11 w-11" /></header>
    <section className="mx-auto mt-7 max-w-md"><div className="relative"><div aria-hidden="true" className="absolute inset-[16%] -z-10 bg-[var(--artwork-halo)] blur-3xl" /><div className="aspect-square overflow-hidden rounded-[var(--radius-artwork)] bg-[var(--bg-2)] shadow-[var(--artwork-bloom)]">{cover ? <img src={cover} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><ListMusic className="h-16 w-16 text-white/15" /></div>}</div></div><div className="mt-7">{beat.sourceType === 'version' ? <ProtocolLabel>Context · {beat.versionType || 'Version'}</ProtocolLabel> : <ProtocolLabel>Main Beat</ProtocolLabel>}<h1 className="mt-3 break-words text-3xl font-semibold leading-tight text-[var(--text-primary)]">{beat.title}</h1><p className="type-small mt-2">{beat.lane?.name || 'Unassigned lane'}{beat.sourceType === 'version' && beat.parentBeatTitle ? ` · From ${beat.parentBeatTitle}` : player.context?.type === 'release' ? ` · ${player.context.title}` : ''}</p><p className="type-protocol-label mt-2 text-[9px]">{player.isLoading ? 'Loading' : player.isPlaying ? 'Playing' : player.isQueueComplete ? 'Complete' : 'Paused'}</p></div>
      <div className="relative mt-6 h-3"><div aria-hidden="true" className="absolute inset-x-0 top-1/2 h-px -translate-y-1/2 bg-white/10"><span className="block h-full bg-[var(--accent)]" style={{ width: `${progress}%` }} /></div><input type="range" min={0} max={player.duration || 0} step={0.1} value={Math.min(player.currentTime, player.duration || 0)} onChange={(event) => player.seek(Number(event.target.value))} disabled={!player.duration} aria-label="Playback progress" className="absolute inset-x-0 -top-4 h-11 w-full cursor-pointer opacity-0 disabled:cursor-not-allowed" /></div><div className="mt-1 flex justify-between type-numeric"><span>{time(player.currentTime)}</span><span>{time(player.duration)}</span></div>
      <div className="mt-6 grid grid-cols-[1fr_auto_auto_auto_1fr] items-center"><button type="button" onClick={player.cycleRepeatMode} className={`justify-self-start grid h-11 min-w-11 place-items-center ${player.repeatMode === 'off' ? 'text-[var(--text-muted)]' : 'text-[var(--accent)]'}`} aria-label={`Repeat ${player.repeatMode}`}><RepeatIcon className="h-5 w-5" /><span className="type-numeric mt-0.5 text-[8px]">{player.repeatMode}</span></button><button type="button" onClick={() => void player.previous()} disabled={!player.hasPrevious && player.currentTime <= 3} className="grid h-12 w-12 place-items-center text-[var(--text-primary)] disabled:opacity-25" aria-label="Previous Beat"><SkipBack className="h-6 w-6" fill="currentColor" /></button><button type="button" onClick={() => void player.togglePlayback()} disabled={player.isLoading} className="grid h-14 w-14 place-items-center rounded-full bg-[var(--text-primary)] text-[var(--bg-0)] disabled:opacity-50" aria-label={player.isPlaying ? 'Pause' : 'Play'}>{player.isLoading ? <LoaderCircle className="h-5 w-5 animate-spin" /> : player.isPlaying ? <Pause className="h-5 w-5" fill="currentColor" /> : <Play className="ml-0.5 h-5 w-5" fill="currentColor" />}</button><button type="button" onClick={() => void player.next()} disabled={!player.hasNext} className="grid h-12 w-12 place-items-center text-[var(--text-primary)] disabled:opacity-25" aria-label="Next Beat"><SkipForward className="h-6 w-6" fill="currentColor" /></button><span className={`justify-self-end grid h-11 min-w-11 place-items-center ${player.shuffle ? 'text-[var(--accent)]' : 'text-[var(--text-muted)]'}`} title={player.shuffle ? 'Shuffled queue' : 'Queue is not shuffled'}><Shuffle className="h-5 w-5" /><span className="type-numeric mt-0.5 text-[8px]">{player.shuffle ? 'on' : 'off'}</span></span></div>
      <button ref={listeningModeEntryRef} type="button" onClick={() => setListeningModeOpen(true)} disabled={!beat} className="focusable-surface mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 border border-[var(--line-subtle)] px-4 text-sm font-semibold text-[var(--text-secondary)] hover:border-white/25 hover:text-[var(--text-primary)] disabled:opacity-40" aria-label="Open Listening Mode"><Expand className="h-4 w-4" aria-hidden="true" /> Listening Mode</button>
      {player.error ? <p className="type-small mt-5 text-center text-[var(--danger)]">{player.error}</p> : null}{slug ? <Link href={`/player/beats/${slug}`} className="focusable-surface mt-4 flex min-h-11 w-full items-center justify-center gap-2 border-y border-[var(--line-subtle)] text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]"><FileAudio className="h-4 w-4" /> Open Beat File</Link> : <button type="button" disabled className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 border-y border-[var(--line-subtle)] text-sm text-[var(--text-muted)]"><FileAudio className="h-4 w-4" /> Beat File unavailable</button>}</section>
    <section className="mx-auto mt-[var(--section-rhythm)] max-w-2xl"><PlaybackQueue compact /></section>
  </main>{isListeningModeOpen ? <ListeningMode onClose={closeListeningMode} /> : null}</>;
}
