'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Play, RotateCcw, Trash2 } from 'lucide-react';
import { clearPlaybackHistory, historyEntryKey, readPlaybackHistory, type PlaybackHistoryEntry } from '@/src/lib/playback-history';
import type { ResolvedHistoryItem } from '@/src/types/player';
import { usePlayer } from './player-provider';
type Row = { history: PlaybackHistoryEntry; item: ResolvedHistoryItem };

export function PlaybackHistorySections() {
  const player = usePlayer(); const [rows, setRows] = useState<Row[]>([]); const [loaded, setLoaded] = useState(false);
  const refresh = useCallback(async () => { const history = readPlaybackHistory(); if (!history.length) { setRows([]); setLoaded(true); return; }
    try { const references = history.map(({ sourceType, beatId, versionKey }) => ({ sourceType, beatId, versionKey })); const response = await fetch('/api/playback-history/resolve', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ references }), cache: 'no-store' }); const payload: { items?: ResolvedHistoryItem[] } = await response.json(); if (!response.ok || !payload.items) throw new Error(); const resolved = new Map(payload.items.map((item) => [historyEntryKey(item), item])); setRows(history.flatMap((entry) => { const item = resolved.get(historyEntryKey(entry)); return item ? [{ history: entry, item }] : []; })); } catch { setRows([]); } finally { setLoaded(true); }
  }, []);
  useEffect(() => { void refresh(); const listener = () => void refresh(); window.addEventListener('kp-playback-history-change', listener); window.addEventListener('storage', listener); return () => { window.removeEventListener('kp-playback-history-change', listener); window.removeEventListener('storage', listener); }; }, [refresh]);
  const continuing = rows.filter(({ history }) => !history.completed && history.position < history.duration * 0.95).slice(0, 6);
  return <>{continuing.length ? <section className="min-w-0"><Label>Continue Listening</Label><h2 className="mt-2 text-xl font-semibold text-white">Pick up where you left off</h2><div className="mt-3 grid min-w-0 gap-3 sm:grid-cols-2">{continuing.map(({ history, item }) => <HistoryCard key={historyEntryKey(history)} item={item} history={history} resume={() => void player.resumeBeat(item, history.position)} />)}</div></section> : loaded ? null : <div aria-hidden="true" className="h-1" />}{rows.length ? <section className="min-w-0"><div className="flex items-center justify-between gap-3"><div><Label>Recently Played</Label><h2 className="mt-2 text-xl font-semibold text-white">Playback history</h2></div><button type="button" onClick={() => { if (window.confirm('Clear playback history on this browser?')) clearPlaybackHistory(); }} className="inline-flex min-h-11 shrink-0 items-center gap-2 text-xs font-semibold text-mist/55 hover:text-white"><Trash2 className="h-4 w-4" /> Clear</button></div><div className="mt-3 grid min-w-0 gap-2">{rows.slice(0, 10).map(({ history, item }) => <RecentRow key={historyEntryKey(history)} item={item} onPlay={() => void player.selectBeat(item, [item], { type: 'manual', title: 'Recently Played' })} />)}</div></section> : null}</>;
}
function HistoryCard({ item, history, resume }: { item: ResolvedHistoryItem; history: PlaybackHistoryEntry; resume: () => void }) { const cover = item.coverArtUrl || item.lane?.fallbackCoverArtUrl; const percent = Math.min(100, Math.max(0, history.position / history.duration * 100)); return <article className="flex min-w-0 gap-3 rounded-2xl border border-white/10 bg-white/5 p-3"><Artwork url={cover} /><div className="min-w-0 flex-1"><p className="truncate font-semibold text-white">{item.title}</p><p className="mt-1 truncate text-xs text-mist/55">{item.sourceType === 'version' ? `${item.versionType || 'Context'} · ${item.parentBeatTitle}` : item.lane?.name || 'Unassigned lane'}</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><span className="block h-full bg-cobalt" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[10px] tabular-nums text-mist/45">{formatTime(history.position)} / {formatTime(history.duration)}</span><button type="button" onClick={resume} className="inline-flex min-h-9 items-center gap-2 rounded-full bg-white px-3 text-xs font-semibold text-ink"><RotateCcw className="h-3.5 w-3.5" /> Resume</button></div></div></article>; }
function RecentRow({ item, onPlay }: { item: ResolvedHistoryItem; onPlay: () => void }) { const cover = item.coverArtUrl || item.lane?.fallbackCoverArtUrl; return <article className="flex min-w-0 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.035] p-3"><Artwork url={cover} small /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{item.title}</p><p className="truncate text-xs text-mist/50">{item.sourceType === 'version' ? `Context · ${item.parentBeatTitle}` : `Main Beat · ${item.lane?.name || 'Unassigned lane'}`}</p>{item.slug ? <Link href={`/player/beats/${item.slug}`} className="text-[10px] uppercase tracking-wider text-cobalt">Beat File</Link> : null}</div><button type="button" onClick={onPlay} aria-label={`Play ${item.title} from beginning`} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-white/10 bg-white/10 text-white"><Play className="h-4 w-4" fill="currentColor" /></button></article>; }
function Artwork({ url, small = false }: { url?: string; small?: boolean }) { return <span className={`${small ? 'h-12 w-12' : 'h-20 w-20'} block shrink-0 overflow-hidden rounded-xl bg-gradient-to-br from-cobalt/40 to-ember/30`}>{url ? <img src={url} alt="" className="h-full w-full object-cover" /> : null}</span>; }
function Label({ children }: { children: React.ReactNode }) { return <p className="text-[10px] uppercase tracking-[0.28em] text-cobalt">{children}</p>; }
function formatTime(seconds: number) { const safe = Math.max(0, Math.floor(seconds)); return `${Math.floor(safe / 60)}:${String(safe % 60).padStart(2, '0')}`; }
