'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Play, RotateCcw, Trash2 } from 'lucide-react';
import { clearPlaybackHistory, historyEntryKey, readPlaybackHistory, type PlaybackHistoryEntry } from '@/src/lib/playback-history';
import type { ResolvedHistoryItem } from '@/src/types/player';
import { MediaArtwork, SectionHeading } from './presentation-primitives';
import { usePlayer } from './player-provider';
type Row = { history: PlaybackHistoryEntry; item: ResolvedHistoryItem };

export function PlaybackHistorySections() {
  const player = usePlayer(); const [rows, setRows] = useState<Row[]>([]); const [loaded, setLoaded] = useState(false);
  const refresh = useCallback(async () => { const history = readPlaybackHistory(); if (!history.length) { setRows([]); setLoaded(true); return; }
    try { const references = history.map(({ sourceType, beatId, versionKey }) => ({ sourceType, beatId, versionKey })); const response = await fetch('/api/playback-history/resolve', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ references }), cache: 'no-store' }); const payload: { items?: ResolvedHistoryItem[] } = await response.json(); if (!response.ok || !payload.items) throw new Error(); const resolved = new Map(payload.items.map((item) => [historyEntryKey(item), item])); setRows(history.flatMap((entry) => { const item = resolved.get(historyEntryKey(entry)); return item ? [{ history: entry, item }] : []; })); } catch { setRows([]); } finally { setLoaded(true); }
  }, []);
  useEffect(() => { void refresh(); const listener = () => void refresh(); window.addEventListener('kp-playback-history-change', listener); window.addEventListener('storage', listener); return () => { window.removeEventListener('kp-playback-history-change', listener); window.removeEventListener('storage', listener); }; }, [refresh]);
  const continuing = rows.filter(({ history }) => !history.completed && history.position < history.duration * 0.95).slice(0, 6);
  return <>{continuing.length ? <section className="min-w-0"><SectionHeading label="Continue Listening" title="Pick up where you left off" /><div className="mt-5 grid min-w-0 gap-4 sm:grid-cols-2">{continuing.map(({ history, item }) => <HistoryCard key={historyEntryKey(history)} item={item} history={history} resume={() => void player.resumeBeat(item, history.position)} />)}</div></section> : loaded ? null : <div aria-hidden="true" className="h-1" />}{rows.length ? <section className="min-w-0"><div className="flex items-end justify-between gap-3"><SectionHeading label="Recently Played" title="Playback history" /><button type="button" onClick={() => { if (window.confirm('Clear playback history on this browser?')) clearPlaybackHistory(); }} className="inline-flex min-h-11 shrink-0 items-center gap-2 text-xs font-semibold text-[var(--text-muted)] hover:text-[var(--text-primary)]"><Trash2 className="h-4 w-4" /> Clear</button></div><div className="mt-5 border-t border-[var(--line-subtle)]">{rows.slice(0, 10).map(({ history, item }) => <RecentRow key={historyEntryKey(history)} item={item} onPlay={() => void player.selectBeat(item, [item], { type: 'manual', title: 'Recently Played' })} />)}</div></section> : null}</>;
}
function HistoryCard({ item, history, resume }: { item: ResolvedHistoryItem; history: PlaybackHistoryEntry; resume: () => void }) { const cover = item.coverArtUrl || item.lane?.fallbackCoverArtUrl; const percent = Math.min(100, Math.max(0, history.position / history.duration * 100)); return <article className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)] gap-4 border border-[var(--line-subtle)] bg-[var(--surface-raised)] p-4"><MediaArtwork src={cover} size="row" /><div className="min-w-0"><p className="truncate font-semibold text-[var(--text-primary)]">{item.title}</p><p className="type-metadata mt-1 truncate">{item.sourceType === 'version' ? `${item.versionType || 'Context'} · ${item.parentBeatTitle}` : item.lane?.name || 'Unassigned lane'}</p><div className="mt-4 h-px overflow-hidden bg-white/10"><span className="block h-full bg-[var(--accent)]" style={{ width: `${percent}%` }} /></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="type-numeric">{formatTime(history.position)} / {formatTime(history.duration)}</span><button type="button" onClick={resume} className="focusable-surface inline-flex min-h-11 items-center gap-2 border-b border-[var(--accent)] px-1 text-xs font-semibold text-[var(--text-primary)]"><RotateCcw className="h-3.5 w-3.5" /> Resume</button></div></div></article>; }
function RecentRow({ item, onPlay }: { item: ResolvedHistoryItem; onPlay: () => void }) { const cover = item.coverArtUrl || item.lane?.fallbackCoverArtUrl; return <article className="grid min-w-0 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-[var(--line-subtle)] py-3"><MediaArtwork src={cover} size="compact" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-[var(--text-primary)]">{item.title}</p><p className="type-metadata mt-1 truncate">{item.sourceType === 'version' ? `Context · ${item.parentBeatTitle}` : `Main Beat · ${item.lane?.name || 'Unassigned lane'}`}</p>{item.slug ? <Link href={`/player/beats/${item.slug}`} className="type-protocol-label mt-1 inline-block text-[9px]">Beat File</Link> : null}</div><button type="button" onClick={onPlay} aria-label={`Play ${item.title} from beginning`} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-[var(--text-primary)] hover:bg-white/[0.06]"><Play className="h-4 w-4" fill="currentColor" /></button></article>; }
function formatTime(seconds: number) { const safe = Math.max(0, Math.floor(seconds)); return `${Math.floor(safe / 60)}:${String(safe % 60).padStart(2, '0')}`; }
