import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ExternalLink, ListMusic } from 'lucide-react';
import { BeatFilePlayer } from '@/src/components/beat-file-player';
import { ContextPlayer } from '@/src/components/context-player';
import { ProtocolLabel, SectionHeading } from '@/src/components/presentation-primitives';
import { PlaylistPreview } from '@/src/components/playlist-preview';
import { youtubePlaylistProviderLabel } from '@/src/lib/youtube-playlist';
import { fetchSanity } from '@/src/sanity/lib/content';
import { beatFileQuery } from '@/src/sanity/lib/queries';
import type { BeatFile } from '@/src/types/beat-file';
type Props = { params: Promise<{ slug: string }> };
const statusLabels: Record<string, string> = { main: 'Main', approvedDemo: 'Approved Demo', sketch: 'Sketch', roughMix: 'Rough Mix', alternateMix: 'Alternate Mix' };
async function getBeat(slug: string) { return fetchSanity<BeatFile | null>(beatFileQuery, null, { slug }); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const beat = await getBeat(slug); if (!beat) return { title: 'Beat Not Found | The Kitsune Protocol' }; const artwork = beat.coverArtUrl || beat.lane?.fallbackCoverArtUrl; const description = beat.shortNote || (beat.lane?.name ? `${beat.title}, a ${beat.lane.name} Beat from The Kitsune Protocol.` : `${beat.title} from The Kitsune Protocol.`); return { title: `${beat.title} | The Kitsune Protocol`, description, openGraph: { title: beat.title, description, images: artwork ? [{ url: artwork }] : undefined } }; }

export default async function BeatFilePage({ params }: Props) { const { slug } = await params; const beat = await getBeat(slug); if (!beat) notFound(); const artwork = beat.coverArtUrl || beat.lane?.fallbackCoverArtUrl; return <main className="mx-auto w-full max-w-3xl pb-6"><Link href="/player" className="editorial-link focusable-surface"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Back to Player</Link>
  <section className="mt-5 grid gap-8 md:grid-cols-[minmax(0,21rem)_minmax(0,1fr)] md:items-end md:gap-12"><div className="relative mx-auto w-full max-w-[21rem] md:mx-0"><div aria-hidden="true" className="absolute inset-[14%] -z-10 bg-[var(--artwork-halo)] blur-3xl" /><div className="aspect-square overflow-hidden rounded-[var(--radius-artwork)] bg-[var(--bg-2)] shadow-[var(--artwork-bloom)]">{artwork ? <img src={artwork} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><ListMusic className="h-14 w-14 text-white/15" /></div>}</div></div><div className="min-w-0"><ProtocolLabel>Beat File</ProtocolLabel><h1 className="mt-4 break-words text-4xl font-semibold leading-[1.04] tracking-[-0.035em] text-[var(--text-primary)] sm:text-5xl">{beat.title}</h1><div className="type-metadata mt-5 flex flex-wrap gap-x-3 gap-y-1"><span>{beat.lane?.name ? beat.lane.slug ? <Link href={`/lanes/${beat.lane.slug}`} className="focusable-surface hover:text-[var(--text-primary)]">{beat.lane.name}</Link> : beat.lane.name : 'Unassigned lane'}</span><span aria-hidden="true">/</span><span>{statusLabels[beat.status || ''] || 'Beat'}</span>{beat.publishedAt ? <><span aria-hidden="true">/</span><span>{formatDate(beat.publishedAt)}</span></> : null}</div>{beat.nsfw ? <p className="type-small mt-5 border-l-2 border-[var(--warning)] pl-3 text-[var(--warning)]">Content warning{beat.nsfwReason ? `: ${beat.nsfwReason}` : ''}</p> : null}<div className="mt-7"><BeatFilePlayer beat={beat} /></div></div></section>
  {beat.shortNote || beat.tags.length ? <section className="mt-10 border-y border-[var(--line-subtle)] py-6">{beat.shortNote ? <p className="type-reading">{beat.shortNote}</p> : null}{beat.tags.length ? <details className="mt-4"><summary className="focusable-surface min-h-11 w-fit cursor-pointer py-3 text-sm text-[var(--text-secondary)]">Archive tags · {beat.tags.length}</summary><p className="type-metadata pb-2">{beat.tags.map((tag) => tag.name).join(' / ')}</p></details> : null}</section> : null}
  {beat.versions.length ? <ArchiveSection label="Alternate states" title="Context"><ContextPlayer parent={{ _id: beat._id, title: beat.title, slug: beat.slug, coverArtUrl: beat.coverArtUrl, lane: beat.lane }} versions={beat.versions} /></ArchiveSection> : null}
  {beat.releases.length ? <ArchiveSection label="Related music" title="Releases"><Rows>{beat.releases.map((item) => <ArchiveRow key={item._id} label={item.releaseType || 'Release'} title={item.title} artwork={item.coverArtUrl} href={item.slug ? `/releases/${item.slug}` : undefined} />)}</Rows></ArchiveSection> : null}
  <Related beat={beat} />
</main>; }

function Related({ beat }: { beat: BeatFile }) { return <>{beat.relatedFixations.length ? <ArchiveSection label="Archive trail" title="Fixations"><Rows>{beat.relatedFixations.map((item) => <ArchiveRow key={item._id} label="Fixation" title={item.title} body={item.shortDescription} href={item.slug ? `/fixations/${item.slug}` : undefined} />)}</Rows></ArchiveSection> : null}{beat.relatedLogs.length ? <ArchiveSection label="Written context" title="Logs"><Rows>{beat.relatedLogs.map((item) => <ArchiveRow key={item._id} label={item.logType || 'Log'} title={item.title || item.body?.slice(0, 80) || 'Untitled thought'} body={item.title ? item.body : undefined} />)}</Rows></ArchiveSection> : null}{beat.relatedLinks.length ? <ArchiveSection label="External trail" title="Links"><Rows>{beat.relatedLinks.map((item) => <a key={item._id} href={item.url} target="_blank" rel="noreferrer noopener" className="grid min-h-16 grid-cols-[1fr_auto] items-center gap-4 border-b border-[var(--line-subtle)] py-4"><span><ProtocolLabel className="text-[var(--text-muted)]">{item.platformOverride || item.platformAuto || 'Saved link'}</ProtocolLabel><span className="mt-2 block font-semibold text-[var(--text-primary)]">{item.title || 'Saved link'}</span></span><ExternalLink className="h-4 w-4 text-[var(--text-muted)]" /></a>)}</Rows></ArchiveSection> : null}{beat.relatedPlaylists.length ? <ArchiveSection label="Listening trail" title="Playlists"><div className="border-t border-[var(--line-subtle)]">{beat.relatedPlaylists.map((item) => <RelatedPlaylist key={item._id} item={item} />)}</div></ArchiveSection> : null}{beat.relatedQuotes.length ? <ArchiveSection label="Other voices" title="Quotes"><div className="border-t border-[var(--line-subtle)]">{beat.relatedQuotes.map((item) => <blockquote key={item._id} className="border-b border-[var(--line-subtle)] py-6"><p className="max-w-2xl text-lg leading-8 text-[var(--text-primary)]">“{item.quoteText}”</p><footer className="type-small mt-3">— {item.person}{item.sourceTitle ? `, ${item.sourceTitle}` : ''}</footer></blockquote>)}</div></ArchiveSection> : null}</>; }
function RelatedPlaylist({ item }: { item: BeatFile['relatedPlaylists'][number] }) { return <article className="border-b border-[var(--line-subtle)] py-5"><h3 className="font-semibold text-[var(--text-primary)]">{item.title}</h3>{item.shortNote ? <p className="type-small mt-2">{item.shortNote}</p> : null}<PlaylistPreview className="mt-4 max-w-xl" title={item.title} spotifyUrl={item.spotifyUrl} spotifyEmbedUrl={item.spotifyEmbedUrl} appleMusicUrl={item.appleMusicUrl} youtubeMusicUrl={item.youtubeMusicUrl} /><div className="flex flex-wrap gap-x-5">{item.spotifyUrl ? <RelatedPlaylistAction href={item.spotifyUrl} label="Spotify" /> : null}{item.appleMusicUrl ? <RelatedPlaylistAction href={item.appleMusicUrl} label="Apple Music" /> : null}{item.youtubeMusicUrl ? <RelatedPlaylistAction href={item.youtubeMusicUrl} label={youtubePlaylistProviderLabel(item.youtubeMusicUrl)} /> : null}</div></article>; }
function RelatedPlaylistAction({ href, label }: { href: string; label: string }) { return <a href={href} target="_blank" rel="noreferrer noopener" className="external-link focusable-surface" aria-label={`Open ${label} in a new tab`}>{label}<ExternalLink aria-hidden="true" className="h-4 w-4" /></a>; }
function ArchiveSection({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <section className="mt-[var(--section-rhythm)]"><SectionHeading label={label} title={title} /><div className="mt-5">{children}</div></section>; }
function Rows({ children }: { children: React.ReactNode }) { return <div className="border-t border-[var(--line-subtle)]">{children}</div>; }
function ArchiveRow({ label, title, body, artwork, href }: { label: string; title: string; body?: string; artwork?: string; href?: string }) { return <article className="grid min-h-16 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-[var(--line-subtle)] py-4"><div className="min-w-0"><ProtocolLabel className="text-[var(--text-muted)]">{label}</ProtocolLabel><h3 className="mt-2 font-semibold text-[var(--text-primary)]">{href ? <Link href={href} className="focusable-surface hover:text-[var(--accent)]">{title}</Link> : title}</h3>{body ? <p className="type-small mt-2 line-clamp-3">{body}</p> : null}</div>{artwork ? <span className="h-14 w-14 overflow-hidden rounded-[var(--radius-artwork)]"><img src={artwork} alt="" className="h-full w-full object-cover" /></span> : null}</article>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(date); }
